import Mathlib.Analysis.Real.Sqrt
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.Combinatorics.SimpleGraph.Clique
import Mathlib.Tactic

#check @Nat.sInf_mem
#check @Nat.sInf_le
#check @Nat.lt_succ_sqrt
#check @Nat.sqrt_le
#check @Nat.le_sqrt
#check @Real.sqrt_le_iff
#check @Real.le_sqrt_of_sq_le
#check @Real.sqrt_le_sqrt
#check @Real.sqrt_sq_eq_abs
#check @SimpleGraph.card_neighborFinset_eq_degree
#check @SimpleGraph.mem_neighborFinset
#check @SimpleGraph.is3Clique_iff
#check @SimpleGraph.degree
#check @Finset.card_biUnion
#check @Finset.card_biUnion_le
#check @Finset.card_erase_of_mem
#check @Fintype.equivFin
#check @Fintype.card_prod
#check @Fintype.card_sum
#check @Fintype.card_fin
#check @Finset.sum_le_sum
#check @Finset.card_map
#check @Filter.Tendsto
#check @Filter.tendsto_atTop
#check @Function.swap
#check @Embedding.comap
#check @Finset.univ
#check @Prod.mk.inj
#check @Fin.castLEEmb
#check @Nat.sub_mul
#check @SimpleGraph.comap
#check @Finset.card_product
#check @Asymptotics.IsTheta
